# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bgd9jkPIaUm3_Tth_FX4zYHN7qsaNGE7
"""

#لدينا هنا كود البايثون الذي سندرب عليه الذكاء الصناعي

# 1 استيراد مكتبات بايثون
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

# 2. تحميل مجموعة بيانات MNIST (وهي مجموعة الأرقام المكتوبة بخط اليد)
print("جاري تحميل مجموعة بيانات MNIST")
(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.mnist.load_data()
print("تم التحميل بنجاح!")

# 3. معالجة الصور وتجهيزها (تطبيع القيم)
#تحويل الأرقام من (0-255) إلى (0-1) من اجل التعلم يكون أسرع
train_images = train_images.reshape((60000, 28, 28, 1)).astype('float32') / 255
test_images = test_images.reshape((10000, 28, 28, 1)).astype('float32') / 255

# 4. بناء نموذج التعلم الآلي باستخدام شبكة CNN (التفافية)
#    هذه هي معمارية العقل الإلكتروني
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')  # 10 خلايا، كل خلية تمثل رقماً من 0 إلى 9
])

# 5. تجميع النموذج (تجهيز بايثون لبدء عملية التعليم)
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# 6. تدريب النموذج (هنا يبدأ الذكاء الاصطناعي بالتعلم فعلياً)
#    بايثون سيمر على الصور 5 مرات متتالية (Epochs=5)
print("بدأ التدريب...")
history = model.fit(train_images, train_labels, epochs=5, batch_size=64)
print("انتهى التدريب!")

# 7. اختبار دقة النموذج على صور لم يرها من قبل
test_loss, test_acc = model.evaluate(test_images, test_labels, verbose=2)
print(f'\nدقة النموذج على بيانات الاختبار: {test_acc * 100:.2f}%')

# 8. حفظ النموذج في ملف (هذا هو "عقل" البرنامج)
model.save('digit_recognition_model.h5')
print("تم حفظ النموذج في ملف اسمه: digit_recognition_model.h5")

# 9. تحميل الملف إلى جهازك (عشان تستخدمه في الخطوات القادمة)
from google.colab import files
files.download('digit_recognition_model.h5')